### ISSUE TITLE
list-fonts-json-binary keeps Extraterm from starting.

### ISSUE THREAD

**Issue by AlexanderLJ** [sedwards2009/extraterm#192]
Not sure what the problem ought to be. I'm running Windows 10 (Build 1809) and Extraterm works fine on my workstation but not on my laptop. I did try copying `list-fonts-json.exe` from that system over, but to no avail.

```---------------------------
list-fonts-json.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

**Comment by sedwards2009** [comment]
Both machines are Windows 10 (Build 1809)? I don't know. May be there is some kind of virus protection etc running on the laptop which isn't on the workstation.

**Comment by AlexanderLJ** [comment]
Both are running windows defender, so I don't think that is it. However, I did compile `list-fonts-json.exe` on my laptop and that worked just fine. I included the binary, maybe it can help. I have the latest version of Visual Studio installed and the 2015 build tools.

[list-fonts-json.zip](https://github.com/sedwards2009/extraterm/files/3156519/list-fonts-json.zip)

**Comment by sedwards2009** [comment]
Thanks for looking into this a bit. I had a look at my compiled version of `list-font-json.exe` and your version using Dependency Walker, and it said that my version had a mix of CPU types in some modules(!). I really don't understand how that could even work, but it seems to run fine most of the time. Your compiled version didn't have have this warning. There must be something wrong or weird about how I built it. I'm not a real Windows dev nor C/C++ dev either, so things could go wrong.

I've set up Azure to build the list-fonts-json git repo at https://dev.azure.com/simon0627/list-fonts-json/_build?definitionId=3&_a=summary The exe it produced was more like your exe and it probably works too. Can you just try it out on your laptop?

[azure-list-fonts-json.zip](https://github.com/sedwards2009/extraterm/files/3159105/azure-list-fonts-json.zip)

**Comment by AlexanderLJ** [comment]
That's very interesting. The Azure build does indeed work fine on my laptop (tested it on my workstation as well just to be sure).

**Comment by sedwards2009** [comment]
thanks for testing. I'll update the exe in the next Extraterm release.

**Comment by sedwards2009** [comment]
Fixed in v0.42.2.

**Comment by tdubuffet** [comment]
Hi,
I have the same error on version 0.42.2.
My windows: Windows 10, version 1903

![image](https://user-images.githubusercontent.com/4500077/59767324-5d594700-92a2-11e9-8ca7-a371a54c899e.png)

Thx

**Comment by hungsu** [comment]
Hello, I just downloaded 0.42.2 but still appear to have the issue

![image](https://user-images.githubusercontent.com/1990680/60892507-3d77cc00-a22d-11e9-8790-9ba549b52e47.png)

**Comment by hungsu** [comment]
So bizarre - I'm not getting the error anymore. Didn't reinstall extraterm, just not getting the error anymore. I had switched to Hyper by Zeit just so I'd have something, then today tried extraterm again and it seems to work. Very very strange. 

Anyway, happy to be back on extraterm :)
